# permissions for end users to view racecourseapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: racecourseapplication-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: racecourse-operator
    app.kubernetes.io/part-of: racecourse-operator
    app.kubernetes.io/managed-by: kustomize
  name: racecourseapplication-viewer-role
rules:
- apiGroups:
  - racecourse.my.domain
  resources:
  - racecourseapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - racecourse.my.domain
  resources:
  - racecourseapplications/status
  verbs:
  - get
