# permissions for end users to edit racecourseapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: racecourseapplication-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: racecourse-operator
    app.kubernetes.io/part-of: racecourse-operator
    app.kubernetes.io/managed-by: kustomize
  name: racecourseapplication-editor-role
rules:
- apiGroups:
  - racecourse.my.domain
  resources:
  - racecourseapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - racecourse.my.domain
  resources:
  - racecourseapplications/status
  verbs:
  - get
